"""
Phase 4: imaging-only baseline -- fine-tune a pretrained ResNet on brain
MRI slices, evaluate with 5-fold patient-level CV, and produce the
per-patient image embeddings Phase 6's fusion model will consume.

Device: auto-detects CUDA and falls back to CPU (`DEVICE` below). Written
to run on Google Colab or Kaggle's free GPU tier -- clone the repo there,
`pip install -r requirements.txt`, make sure data/processed/patient_cohort.csv
and data/processed/patient_folds.csv exist (copy them over; they're small
and gitignored), then `python src/models/mri_model.py`. No local paths are
hardcoded anywhere in this file. It also runs on CPU (just slower) with no
code changes -- use --smoke-test for a fast correctness check on a laptop
before committing to a full GPU run.

Pooling strategy (decided before writing this script, not after): each
patient contributes 115 slices (see mri_dataset.py). To get one prediction
and one feature vector per patient, this script AVERAGES THE PER-SLICE
EMBEDDINGS (the 512-dim penultimate-layer output) into one pooled vector
per patient, then applies the trained linear head to that pooled vector --
it does NOT average 115 per-slice probabilities into one probability.
Pooling at the embedding stage keeps the full 512 dimensions of
information for Phase 6's fusion layer to combine with the EHR features;
pooling at the probability stage would collapse each patient down to a
single scalar before fusion ever saw the image data. The same pooled
embedding is also what this script uses to compute its own imaging-only
baseline metrics (AUROC/sensitivity/specificity), so the baseline numbers
and the fusion inputs are produced the same way.

Nested fold consistency: for fold k, the CNN is trained only on fold k's
training patients (patient_folds.csv), then used to embed ALL 298
patients -- its own training patients and its held-out validation
patients alike. Phase 6 must use fold k's embeddings file for fold k's
fusion training/eval, and never mix embeddings generated by one fold's
model with another fold's split. Mixing them would leak: a patient's
embedding would come from a model that never saw the *inputs* it's
generated from as training data, but a *different* patient's fold
assignment might not line up, silently breaking the split.

Outputs (all under data/processed/):
  - checkpoints/mri_fold{k}.pt          -- trained backbone+head weights
                                            (gitignored -- large binaries
                                            never get committed)
  - mri_embeddings_fold{k}.csv          -- pooled 512-dim embedding + prob
                                            for all 298 patients, tagged
                                            train/val for that fold
                                            (committed -- see .gitignore's
                                            explicit exception for these
                                            5 files by name)
  - mri_baseline_metrics.csv            -- per-fold AUROC/sensitivity/
                                            specificity + the mean/std
                                            summary row Phase 9's README
                                            comparison table will use
                                            (committed, same exception)

Not this script's job: a final model trained on all 298 patients for
deployment (Phase 8's concern) -- this script only produces the 5
fold-specific models needed for a fair CV comparison.

Resumability: free Colab/Kaggle GPU sessions can disconnect mid-run, so
each fold's checkpoint, embeddings CSV, and metrics row are all saved to
disk immediately after that fold finishes -- not batched up and written
once at the very end. A fold's embeddings CSV existing on disk is treated
as proof that fold already completed; simply re-running the script skips
straight past any such fold and picks up training from the first one
that's still missing its output. To force a fold to redo from scratch,
delete its mri_embeddings_fold{k}.csv (and, if you want a fresh checkpoint
too, its mri_fold{k}.pt) before re-running. --smoke-test never persists
anything, so it always runs regardless of what real output exists.
"""
import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.metrics import confusion_matrix, roc_auc_score
from torch.utils.data import DataLoader
from torchvision.models import ResNet18_Weights, ResNet34_Weights, resnet18, resnet34

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src" / "data"))
from folds import load_patient_folds, patients_in_split  # noqa: E402
from mri_dataset import MRIDataset  # noqa: E402

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
RANDOM_SEED = 42

_BACKBONES = {
    "resnet18": (resnet18, ResNet18_Weights.IMAGENET1K_V1),
    "resnet34": (resnet34, ResNet34_Weights.IMAGENET1K_V1),
}


class MRIClassifier(nn.Module):
    """Pretrained ResNet backbone + a linear head. forward() returns
    (logit, embedding): embedding is the 512-dim (resnet18) penultimate-
    layer output that gets pooled per patient per the strategy above."""

    def __init__(self, arch: str = "resnet18"):
        super().__init__()
        backbone_fn, weights = _BACKBONES[arch]
        self.backbone = backbone_fn(weights=weights)
        self.embedding_dim = self.backbone.fc.in_features
        self.backbone.fc = nn.Identity()
        self.head = nn.Linear(self.embedding_dim, 1)

    def forward(self, x: torch.Tensor):
        embedding = self.backbone(x)
        logit = self.head(embedding).squeeze(-1)
        return logit, embedding

    def predict_from_embedding(self, embedding: torch.Tensor) -> torch.Tensor:
        return torch.sigmoid(self.head(embedding).squeeze(-1))


def train_one_fold(model: MRIClassifier, train_dataset: MRIDataset, args: argparse.Namespace) -> None:
    labels = np.array(train_dataset.labels)
    n_pos, n_neg = (labels == 1).sum(), (labels == 0).sum()
    pos_weight = torch.tensor(n_neg / max(n_pos, 1), dtype=torch.float32, device=DEVICE)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=(DEVICE.type == "cuda"),
    )

    model.train()
    for epoch in range(args.epochs):
        running_loss = 0.0
        for images, batch_labels, _ in loader:
            images = images.to(DEVICE)
            batch_labels = batch_labels.float().to(DEVICE)

            optimizer.zero_grad()
            logits, _ = model(images)
            loss = criterion(logits, batch_labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * images.size(0)

        logger.info("  epoch %d/%d - train loss %.4f", epoch + 1, args.epochs, running_loss / len(train_dataset))


def extract_pooled_embeddings(
    model: MRIClassifier, dataset: MRIDataset, args: argparse.Namespace
) -> tuple[dict, dict]:
    """Mean-pool each patient's slice embeddings. Returns
    (patient_id -> pooled embedding tensor, patient_id -> label)."""
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=(DEVICE.type == "cuda"),
    )

    model.eval()
    embedding_sums, slice_counts, labels_by_patient = {}, {}, {}
    with torch.no_grad():
        for images, batch_labels, patient_ids in loader:
            images = images.to(DEVICE)
            _, embeddings = model(images)
            embeddings = embeddings.cpu()
            for embedding, label, patient_id in zip(embeddings, batch_labels, patient_ids):
                embedding_sums[patient_id] = embedding_sums.get(patient_id, 0.0) + embedding
                slice_counts[patient_id] = slice_counts.get(patient_id, 0) + 1
                labels_by_patient[patient_id] = int(label)

    pooled = {pid: embedding_sums[pid] / slice_counts[pid] for pid in embedding_sums}
    return pooled, labels_by_patient


def embeddings_path_for(fold: int, out_dir: Path) -> Path:
    return out_dir / f"mri_embeddings_fold{fold}.csv"


def save_fold_metrics(metrics_path: Path, fold_metrics: dict) -> None:
    """Upsert one fold's row into the shared metrics CSV immediately, so a
    fold's results survive even if the process is killed/disconnected
    before the remaining folds finish. This is what main()'s resume check
    reads back for folds it skips."""
    if metrics_path.exists():
        existing = pd.read_csv(metrics_path)
        existing = existing[existing["fold"] != fold_metrics["fold"]]
        updated = pd.concat([existing, pd.DataFrame([fold_metrics])], ignore_index=True)
    else:
        updated = pd.DataFrame([fold_metrics])
    updated.sort_values("fold").reset_index(drop=True).to_csv(metrics_path, index=False)


def run_fold(fold: int, mri_cohort: pd.DataFrame, folds_df: pd.DataFrame, args: argparse.Namespace) -> dict:
    torch.manual_seed(RANDOM_SEED)
    train_ids = set(patients_in_split(folds_df, fold, "train"))
    val_ids = set(patients_in_split(folds_df, fold, "val"))

    if args.smoke_test:
        train_ids = set(list(train_ids)[:3])
        val_ids = set(list(val_ids)[:2])
        mri_cohort = mri_cohort[mri_cohort["patient_id"].isin(train_ids | val_ids)]

    train_cohort = mri_cohort[mri_cohort["patient_id"].isin(train_ids)]
    train_dataset = MRIDataset(train_cohort)

    logger.info("Fold %d: training on %d patients (%d slices)", fold, len(train_cohort), len(train_dataset))
    model = MRIClassifier(args.arch).to(DEVICE)
    train_one_fold(model, train_dataset, args)

    full_dataset = MRIDataset(mri_cohort)
    pooled_embeddings, patient_labels = extract_pooled_embeddings(model, full_dataset, args)

    model.eval()
    rows = []
    with torch.no_grad():
        for patient_id, embedding in pooled_embeddings.items():
            prob = model.predict_from_embedding(embedding.unsqueeze(0).to(DEVICE)).item()
            row = {
                "patient_id": patient_id,
                "split": "train" if patient_id in train_ids else "val",
                "label": patient_labels[patient_id],
                "prob": prob,
            }
            row.update({f"emb_{i}": v for i, v in enumerate(embedding.tolist())})
            rows.append(row)
    fold_df = pd.DataFrame(rows)

    val_rows = fold_df[fold_df["split"] == "val"]
    auroc = roc_auc_score(val_rows["label"], val_rows["prob"])
    val_preds = (val_rows["prob"] >= 0.5).astype(int)
    tn, fp, fn, tp = confusion_matrix(val_rows["label"], val_preds, labels=[0, 1]).ravel()
    sensitivity = tp / (tp + fn) if (tp + fn) else float("nan")
    specificity = tn / (tn + fp) if (tn + fp) else float("nan")

    fold_metrics = {
        "fold": fold,
        "n_val": len(val_rows),
        "auroc": auroc,
        "sensitivity": sensitivity,
        "specificity": specificity,
    }
    logger.info(
        "Fold %d val metrics (n=%d): AUROC=%.3f sensitivity=%.3f specificity=%.3f",
        fold, len(val_rows), auroc, sensitivity, specificity,
    )

    if not args.smoke_test:
        out_dir = REPO_ROOT / "data" / "processed"
        checkpoint_dir = out_dir / "checkpoints"
        checkpoint_dir.mkdir(parents=True, exist_ok=True)
        torch.save(model.state_dict(), checkpoint_dir / f"mri_fold{fold}.pt")
        fold_df.to_csv(embeddings_path_for(fold, out_dir), index=False)
        save_fold_metrics(out_dir / "mri_baseline_metrics.csv", fold_metrics)
        logger.info("Fold %d: checkpoint, embeddings, and metrics row saved to disk.", fold)

    return fold_metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase 4: MRI imaging-only baseline, 5-fold CV")
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--arch", choices=list(_BACKBONES), default="resnet18")
    parser.add_argument("--folds", type=str, default=None, help="Comma-separated fold indices to run, e.g. '0,1'. Default: all folds.")
    parser.add_argument("--smoke-test", action="store_true", help="Tiny run (few patients, 1 epoch) to check the pipeline works; skips saving checkpoints/embeddings.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    logger.info("Using device: %s", DEVICE)

    cohort = pd.read_csv(REPO_ROOT / "data" / "processed" / "patient_cohort.csv")
    folds_df = load_patient_folds(REPO_ROOT / "data" / "processed" / "patient_folds.csv")
    mri_cohort = cohort[cohort["patient_id"].isin(folds_df["patient_id"])].reset_index(drop=True)

    available_folds = sorted(folds_df["fold"].unique())
    folds_to_run = [int(f) for f in args.folds.split(",")] if args.folds else available_folds
    if args.smoke_test:
        folds_to_run = folds_to_run[:1]
        args.epochs = 1

    out_dir = REPO_ROOT / "data" / "processed"
    metrics_path = out_dir / "mri_baseline_metrics.csv"

    all_metrics = []
    for fold in folds_to_run:
        embeddings_path = embeddings_path_for(fold, out_dir)
        if not args.smoke_test and embeddings_path.exists():
            logger.info("Fold %d already completed (%s exists) -- skipping, not retraining.", fold, embeddings_path.name)
            continue
        all_metrics.append(run_fold(fold, mri_cohort, folds_df, args))

    if args.smoke_test:
        logger.info("\n%s", pd.DataFrame(all_metrics).to_string(index=False))
        return

    # Read the metrics file back from disk rather than relying only on
    # `all_metrics` -- any fold skipped above as already-done has its
    # numbers on disk already, not in this run's in-memory list.
    final_metrics_df = pd.read_csv(metrics_path) if metrics_path.exists() else pd.DataFrame(all_metrics)
    logger.info("\n%s", final_metrics_df.to_string(index=False))
    summary = final_metrics_df[["auroc", "sensitivity", "specificity"]].agg(["mean", "std"])
    logger.info("Summary across folds:\n%s", summary)


if __name__ == "__main__":
    main()
